name = "daycare-helper"
main = "worker.js"
compatibility_date = "2026-06-26"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
DEFAULT_TEACHER_NAME = "김선생님"
DEFAULT_CLASS_NAME = "햇살반"
NOTION_VERSION = "2022-06-28"
GEMINI_MODEL = "gemini-3.8-flash"
NOTION_PROXY_URL = "https://minmin-notion.awslike6.workers.dev"
NOTION_TEACHER_DB_ID = "3e0a2711-5b68-8186-ad30-cbaea7687006"
NOTION_CHILD_DB_ID = "3e0a2711-5b68-8182-955e-f116e4174e3a"
NOTION_DAILY_LOG_DB_ID = "3e0a2711-5b68-8122-9eea-dd49bf8a625c"

